= Music-Free Manifesto

Reprodukce hudby se díky mnoha internetvým službám a kapesním přehrávačům stala být pro kohokoliv natolik dostupná, že již skoro není možné navštívit místa, kde by vás nepotkala. Od stánků s občerstvením po "luxusní" obchodz, které hlučí  a často i promítají přímo do výloh a ulic až po..., a to nám vadí především, místa pro setkávání jako jsou kavárny a restaurace.

Právě na těchto místech lze pozorovat neřízené pouštění vlastního *playlistu* obshluhou, která je dnes v restauracích a hlavně kavárnách především "nekvalifikovaná" a provozuje jí kdejaký brigádník a student.

Hudba v těchto podnicích je v lepším případě vata a v horším případě si ji všimnete. Možná, že dokonce hrají vaši oblíbenou kapelu, pokud máte štěstí. Máte ale náladu na vaši oblíbenou kapelu či píseň i když jste si ji zrovna pustit nechtěli? Přestanete navštěvovat všechny podniky, kde vám hudbu nutí? Zřejmě ne, protože takových podniků je dnes většina. Proto vznikl tento manifest!

Jsme proti reprodukci a pouštění hudby v kavárnách, restauracích a jiných podnicích, které nejsou primárně určeny pro poslech hudby nebo, které nemají proto vyharzené hodiny. 

Máte v kavárně trapné ticho? Možná že není tak trapné, možná je to jen pocit, kterému se bráníte, protože ticho obnažuje vaše myšlenky. Vadí vám, že slyšíte a jste slyšeni? Proč tedy chodíte se svými rozhovory na veřejná místa a proč provozujete kavárnu nebo restauraci?

Tento manifest není o tom, ukázat jak kvalitní, či nekvalitní hudba se na veřejných místech pouští, ale že i hudba má své místo a čas a že návštěvník by měl mít možnost volby, co chce a nechce poslouchat a v neposled i možnost spočinout v tichu, když všude venku je hluku dost. Jsme proti hudebnímu smogu ve veřejném prostoru.

NÁLEPKOU __MUSIC-FREE__ NEVYJADŘUJETE NESYMPATIE K HUDBĚ ČI KULTUŘE, ALE NAOPAK UKAZUJETE, ŽE SI JI VÁŽÍTE A VÍTE KDE MÁ SVÉ MÍSTO A ČAS A STEJNĚ TAK UKAZUJETE, ŽE SI VÁŽÍTE SVÉHO NÁVŠTĚVNÍKA. 