TARGET=program
CC=gcc
CFLAGS=-std=c99 -Wall - Werror -Wextra -pedantic
LDFLAGS=
SOURCES=./src/*.c
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=main

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.c.o:
	$(CC) $(CFLAGS) $< -o $@