= Paleontologie Stratigrafie a Historická Geologie

== Geologická období

* Paleozoikum
  - Kambrium 
  - Ordovik
  - Silur 
  - Devon 
  - Karbon
  - Perm

* Mezozoikum
  - Trias
  - Jura
  - Křída

* Kenozoikum
* Paleogén
* Neogén

Organismy si začaly tvořit pevné schránky na přelomu prekambria a kambria

Fe^2+ je ve vodě rozpustné
oxidací na Fe^3+ se stane nerozpustným

Páskované rudy (jaspilit)

Po začátku kambria stoupá hladina kyslíku.
Kyslíku bylo v karbonu až o 50% více, díky romu členovci mohli dosahovat gigantických rozměrů.
např. Tracheáti (hmyz; vážky), Artopleura

Karbon byl jedno z nejchladnějších období a pohřbývalo se velké množství uhlíku.
Většinou platí, že když stoupá kyslík, tak většinou klesá podíl skleníkových plynů a tendenci se ochlazovat.

Stromatolity, střídání organických (organický mat) a anorganických vrstviček.
Pokud do roganického matu pustíme příliv a odliv, který začne při odlivu přetvářet -- cestičky.

Asi před miliardou let se přestávají objevovat, zřejmě se objevily organismy, které je výrazně požírají.

1) mikrofosílie
2) stromatolity 
3) makrofosílie (uhlíkaté) řasy

Definice útesů
typy útesů: biohermy a biostromy
