#!/bin/sh

# Zamezíme `push` do zadané větve.

pattern="$1"

branch=`git rev-parse --abbrev-ref HEAD`

#echo $branch
#echo $pattern

if [[ "$branch" == "$pattern" ]]; then
	echo "Branch $branch is protected." 
	return  1
fi

return 0ven