= Cephalopoda

(Skupinu přednáší Košták)

Centralizovaná nervová soustava v hlavové části, 
Predace souvisí s rozvojem inteligence?
radula 
homolice
žábry umístěné za srdcem 
nemají operkulum

hlavnožoci, schránky mají přímé i stočené 
sifonální trubice probíhá u recentní loděnky středem, u fosilních zástupců různě excentrická
žili v mělkých šelfových mořích ale postupně se dostávají do větších hloubek
dnešní loděnka se pohybuje vertikálně i stovky metrů
současná loděnka nemá larvální stádium
to osuvisí s   

=== Endoceras
https://en.wikipedia.org/wiki/Endoceras

=== Actinoceratiti

=== Ortoceratiti

- fosilní zástupci měli larvální stádium?
- dlouhověkost u fosilních zástupců?

Od karbonu do křídy je stratigrafie založena z velké části na amonitech

Sifonální trubice je na hřbetní straně s jednou výjimkou 
Způsob uchycení sept je označován jako šev, zesložitování švu => zvetšuje pevnost
schránky a může tak odolávat velkým tlakům.

=== Amoniti

- aragonatitový 

Z amonit se zachovávají "víčka" tzv. aptycha = kalcitové orgány
jsou spíše masivní spodní čelisti.

Existují dvě kompenzační hloubky:

* kalcitová (hlouběji)
* aragonitová => pod touto hranicí se rozpouští aragonit
